service: diagnal-workshop-v3

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_NAME}"
  environment:
    REGION: ${opt:region, self:provider.region}
    DYNAMODB_TABLE_NAME: ScrappedSites

package:
 patterns:
   - '!coverage'
   - '!tests'
   - '!README.md'
   - '!LICENSE'
   - '!.npmignore'
   - '!.nyc_output'

functions:
  metaDataScrapper:
    handler: handler.getMetaData
    events:
      - http:
          path: /
          method: post

resources:
  Resources:
    DynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: url
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          -
            AttributeName: url
            KeyType: HASH
        TableName: ${self:provider.environment.DYNAMODB_TABLE_NAME}