service: diagnal-workshop-v3

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_NAME}"
  environment:
    DYNAMODB_TABLE_NAME: ScrappedSites

# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.js'
#    - '!exclude-me-dir/**'
#    - include-me.js
#    - include-me-dir/**

functions:
  metaDataScrapper:
    handler: handler.getMetaData
    events:
      - http:
          path: /
          method: post

resources:
  Resources:
    DynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: url
            AttributeType: S
          -
            AttributeName: createdAt
            AttributeType: N
          -
            AttributeName: metaData
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          -
            AttributeName: url
            KeyType: HASH
          -
            AttributeName: createdAt
            KeyType: RANGE
        TableName: ${self:provider.environment.DYNAMODB_TABLE_NAME}